In [1]:
# 1) Create Two numpy array of size 3 X 2 and 2 X 3
import pandas as pd
import numpy as np
import random

In [11]:
nparr1=np.empty(shape=(3,2))
print(nparr1)
nparr2=np.empty(shape=(2,3))
print(nparr2)

a = np.zeros((3,2), dtype=int)
print(a)
a = np.zeros((2,3), dtype=int)
print(a)

a = np.ones((3,2), dtype=int)
print(a)
a = np.ones((2,3), dtype=int)
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]]
[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]
 [1 1]]
[[1 1 1]
 [1 1 1]]


In [12]:
# 2) Randomly Initalize above two array
for i in range(3):
    for j in range(2):
        nparr1[i][j]=random.randint(1,20)
        nparr2[j][i]=random.randint(1,20)
print(nparr1)
print(nparr2)

[[12. 18.]
 [10. 10.]
 [ 6. 12.]]
[[ 1. 16. 10.]
 [ 2.  5. 19.]]


In [13]:
# Perform matrix multiplication 3*2 2*3 => 3*3
matrixmul=nparr1.dot(nparr2)
print(matrixmul)

[[ 48. 282. 462.]
 [ 30. 210. 290.]
 [ 30. 156. 288.]]


In [15]:
# 4) Perform elementwise matrix multiplication
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
elementwisemul=np.multiply(a,b)
print(elementwisemul)

output = a*b
print(output)

[[ 7 16 27]
 [40 55 72]]
[[ 7 16 27]
 [40 55 72]]


In [16]:
# 5) Find mean of first matrix
meanmatrix=np.mean(nparr1)
print(meanmatrix)

11.333333333333334


In [46]:
# 6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version
data = pd.read_csv('https://gist.githubusercontent.com/ZeccaLehn/4e06d2575eb9589dbe8c365d61cb056c/raw/64f1660f38ef523b2a1a13be77b002b98665cdfe/mtcars.csv')
datatop=data.columns
print(datatop)

Index(['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')


In [45]:
for i in range(1,len(datatop)):
    data[datatop[i]]-=np.mean(data[datatop[i]])
print(data)

             Unnamed: 0        mpg     cyl        disp        hp      drat  \
0             Mazda RX4   0.909375 -0.1875  -70.721875  -36.6875  0.303437   
1         Mazda RX4 Wag   0.909375 -0.1875  -70.721875  -36.6875  0.303437   
2            Datsun 710   2.709375 -2.1875 -122.721875  -53.6875  0.253438   
3        Hornet 4 Drive   1.309375 -0.1875   27.278125  -36.6875 -0.516562   
4     Hornet Sportabout  -1.390625  1.8125  129.278125   28.3125 -0.446563   
5               Valiant  -1.990625 -0.1875   -5.721875  -41.6875 -0.836563   
6            Duster 360  -5.790625  1.8125  129.278125   98.3125 -0.386562   
7             Merc 240D   4.309375 -2.1875  -84.021875  -84.6875  0.093437   
8              Merc 230   2.709375 -2.1875  -89.921875  -51.6875  0.323437   
9              Merc 280  -0.890625 -0.1875  -63.121875  -23.6875  0.323437   
10            Merc 280C  -2.290625 -0.1875  -63.121875  -23.6875  0.323437   
11           Merc 450SE  -3.690625  1.8125   45.078125   33.3125