In [17]:
import numpy as np

## Training Data

In [18]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [19]:
# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.38543475 0.73325359 0.6479768 ]
 [0.82524246 0.90869246 0.08257533]]
Biases:
[[0.61126529 0.8380764 ]
 [0.11649176 0.40864863]
 [0.55543375 0.88124474]
 [0.23277924 0.82481961]
 [0.43940398 0.08652995]
 [0.99576571 0.82401352]
 [0.13393466 0.58576342]
 [0.65171017 0.3979084 ]
 [0.57125888 0.63393846]
 [0.08816562 0.98205356]
 [0.62926131 0.76289623]
 [0.2172487  0.84556151]
 [0.04531127 0.20973603]
 [0.45095226 0.49300406]
 [0.82664889 0.10201034]]


In [20]:
# Define the model
def model(x):
    return x @ np.transpose(weights) + biases

In [21]:
# Generate predictions
preds = model(inputs)

In [22]:
# Compare with targets
print("Predictions : ", preds, sep="\n")
print("Targets : ",targets, sep="\n")

Predictions : 
[[105.73899541 125.51391005]
 [141.18788572 160.75547021]
 [169.92689317 199.23149761]
 [ 95.0521701  127.12861355]
 [142.78512297 150.0430091 ]
 [106.12349583 125.49984717]
 [141.20532863 160.93258499]
 [170.02316958 198.74816127]
 [ 95.39064974 126.9377324 ]
 [142.43388462 150.93853271]
 [105.75699143 125.43872989]
 [141.28864266 161.19238308]
 [169.41677069 198.5599889 ]
 [ 95.27034312 126.796798  ]
 [143.17236788 150.05848949]]
Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [23]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [24]:
# Compute loss
loss = mse(preds, targets)
print(loss)

7145.231182716117


In [25]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print("weights_grad:",weights_grad, sep="\n")
print("biases_grad:",biases_grad, sep="\n")

weights_grad:
[[ 9502.52443473  8966.78699851  5776.17816732]
 [10629.453819    9877.87549378  6225.97907793]]
biases_grad:
[[ 6.63186605  7.40185467]
 [ 8.02505143  7.96739603]
 [ 6.79025242  8.83086635]
 [ 9.74028935 12.01714847]
 [ 5.30468306  4.13906788]
 [ 6.68313278  7.39997962]
 [ 8.02737715  7.99101133]
 [ 6.80308928  8.7664215 ]
 [ 9.78541997 11.99169765]
 [ 5.25785128  4.25847103]
 [ 6.63426552  7.39183065]
 [ 8.03848569  8.02565108]
 [ 6.72223609  8.74133185]
 [ 9.76937908 11.9729064 ]
 [ 5.35631572  4.14113193]]


## Adjust weights

In [26]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [27]:
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.29040951 0.64358572 0.59021502]
 [0.71894792 0.8099137  0.02031554]]
Biases:
[[0.61119897 0.83800238]
 [0.11641151 0.40856896]
 [0.55536585 0.88115643]
 [0.23268184 0.82469944]
 [0.43935093 0.08648856]
 [0.99569888 0.82393952]
 [0.13385439 0.58568351]
 [0.65164213 0.39782074]
 [0.57116103 0.63381854]
 [0.08811304 0.98201098]
 [0.62919497 0.76282232]
 [0.21716831 0.84548125]
 [0.04524405 0.20964862]
 [0.45085457 0.49288433]
 [0.82659533 0.10196893]]


In [28]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

3420.0054783309724


In [29]:
# repeating same for 200 times
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [30]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

54.42199091847272


In [31]:
# Print predictions
print(preds)

[[ 57.92236686  71.73134156]
 [ 81.4110373   95.97409671]
 [119.02882273 141.70176257]
 [ 23.69803817  42.91199107]
 [ 99.53140102 107.58717911]
 [ 58.30676425  71.71728245]
 [ 81.42847553  96.15116404]
 [119.12507334 141.21855575]
 [ 24.03642711  42.72116106]
 [ 99.18025679 108.48246275]
 [ 57.94035806  71.65618154]
 [ 81.51176724  96.41089251]
 [118.51883694 141.0304338 ]
 [ 23.91615273  42.58026443]
 [ 99.91854217 107.60265535]]


In [32]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
