In [35]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [36]:
# Imports
import torch.nn as nn

In [37]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [38]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [39]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [40]:
# Define dataset
dataset = TensorDataset(inputs, targets)
dataset[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [41]:
# Define data loader
batch_size = 5
DL = DataLoader(dataset, batch_size, shuffle=True)
next(iter(DL))

[tensor([[ 73.,  67.,  43.],
         [ 87., 134.,  58.],
         [ 91.,  88.,  64.],
         [ 73.,  67.,  43.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [119., 133.],
         [ 81., 101.],
         [ 56.,  70.],
         [119., 133.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [42]:
# Define model
final_model = nn.Linear(3, 2)
print(final_model.weight, end="\n---------\n")
print(final_model.bias)

Parameter containing:
tensor([[ 0.0515,  0.0868, -0.0216],
        [-0.3840,  0.0059,  0.5498]], requires_grad=True)
---------
Parameter containing:
tensor([-0.5346, -0.3781], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [43]:
# Define optimizer
opt = torch.optim.SGD(final_model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [44]:
# Import nn.functional
import torch.nn.functional as F

In [45]:
# Define loss function
loss_fn = F.mse_loss

In [46]:
loss = loss_fn(final_model(inputs) , targets)
print(loss)

tensor(7529.5132, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [47]:
# Define a utility function to train the model
def fit(num_epochs, final_model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in DL:
            # Generate predictions
            pred = final_model(xb)
            loss = loss_fn(pred,yb)
            # Perform gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(final_model(inputs), targets))

In [48]:
# Train the model for 100 epochs
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(13.3286, grad_fn=<MseLossBackward>)


In [49]:
# Generate predictions
preds = final_model(inputs)
preds

tensor([[ 58.3657,  70.7953],
        [ 80.5918, 100.9532],
        [120.3075, 131.4089],
        [ 28.4358,  40.2996],
        [ 94.7227, 117.6485],
        [ 58.3657,  70.7953],
        [ 80.5918, 100.9532],
        [120.3075, 131.4089],
        [ 28.4358,  40.2996],
        [ 94.7227, 117.6485],
        [ 58.3657,  70.7953],
        [ 80.5918, 100.9532],
        [120.3075, 131.4089],
        [ 28.4358,  40.2996],
        [ 94.7227, 117.6485]], grad_fn=<AddmmBackward>)

In [50]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [51]:
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(4.0251, grad_fn=<MseLossBackward>)


#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
#Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 